const Images = {
  splash: require("../assets/Images/splash.png"),
  arrow_next: require("../assets/Images/arrow_next.png"),
  logo: require("../assets/Images/logo.png"),
  arrow_back_header: require("../assets/Images/arrow_back_header.png"),
  backspace_black: require("../assets/Images/backspace_black.png"),
  search_icon: require("../assets/Images/search_icon.png"),
  arrow_select_code: require("../assets/Images/arrow_select_code.png"),
  content_copy: require("../assets/Images/content_copy.png"),
  walletHeader: require("../assets/Images/walletHeader.png"),

  check_box_outline: require("../assets/Images/check_box_outline.png"),
  checkbox_selected: require("../assets/Images/checkbox_selected.png"),
  list_default_icon: require("../assets/Images/list_default_icon.png"),
  icon_terms_selected: require("../assets/Images/icon_terms_selected.png"),

  icon_nav_earn: require("../assets/Images/icon_nav_earn.png"),
  icon_nav_earn_active: require("../assets/Images/icon_nav_earn_active.png"),
  icon_nav_marketplace: require("../assets/Images/icon_nav_marketplace.png"),
  icon_nav_marketplace_active: require("../assets/Images/icon_nav_marketplace_active.png"),
  icon_wallet: require("../assets/Images/icon_wallet.png"),
  icon_wallet_active: require("../assets/Images/icon_wallet_active.png"),
  icon_setting_nav: require("../assets/Images/icon_setting_nav.png"),
  icon_setting_nav_active: require("../assets/Images/icon_setting_nav_active.png"),

  icon_send: require("../assets/Images/icon_send.png"),
  icon_receive: require("../assets/Images/icon_receive.png"),
  wallet_notification: require("../assets/Images/icon_notification.png"),
  wallet_notification_active: require("../assets/Images/icon_notification_red.png"),
  wallet_option_icon: require("../assets/Images/wallet_option_icon.png"),
  icon_swap_wallet: require("../assets/Images/icon_swap_wallet.png"),

  india_flag: require("../assets/Images/india_flag.png"),
  icon_lock_profile: require("../assets/Images/icon_lock_profile.png"),
  avatar_profie: require("../assets/Images/avatar_profie.png"),
  profile_verified_icon: require("../assets/Images/profile_verified_icon.png"),
  arrow_right: require("../assets/Images/arrow_right.png"),
  upload_img_icon: require("../assets/Images/upload_img_icon.png"),

  icon_document_kyc: require("../assets/Images/icon_document_kyc.png"),
  add_doc_icon: require("../assets/Images/add_doc_icon.png"),
  icon_upload_doc: require("../assets/Images/icon_upload_doc.png"),
  upload_document_success: require("../assets/Images/upload_document_success.png"),
  upload_doc_cancel: require("../assets/Images/upload_doc_cancel.png"),
  icon_address: require("../assets/Images/icon_address.png"),
  dropdonw_icon: require("../assets/Images/dropdonw_icon.png"),
  icon_bnb: require("../assets/Images/icon_bnb.png"),
  icon_bnb_smartchain: require("../assets/Images/icon_bnb_smartchain.png"),
  advance_setting_icon: require("../assets/Images/advance_setting_icon.png"),
  icon_confirmation_send: require("../assets/Images/icon_confirmation_send.png"),

  icon_helpSupport: require("../assets/Images/icon_helpSupport.png"),
  icon_privacy: require("../assets/Images/icon_privacy.png"),
  icon_prefrence: require("../assets/Images/icon_prefrence.png"),
  icon_invite_earn: require("../assets/Images/icon_invite_earn.png"),
  icon_security: require("../assets/Images/icon_security.png"),
  icon_wallet_and_backup: require("../assets/Images/icon_wallet_and_backup.png"),
  icon_reward: require("../assets/Images/icon_reward.png"),
  my_badges: require("../assets/Images/my_badges.png"),
  icon_kyc: require("../assets/Images/icon_kyc.png"),
  icon_personal_profile: require("../assets/Images/icon_personal_profile.png"),
  forgot_icon: require("../assets/Images/forgot_icon.png"),

  radio_default: require("../assets/Images/radio_default.png"),
  radio_selected: require("../assets/Images/radio_selected.png"),
  select_arrow: require("../assets/Images/select_arrow.png"),
  unverified_icon: require("../assets/Images/unverified.png"),
  pending_icon: require("../assets/Images/pending.png"),
  declined_icon: require("../assets/Images/declined.png"),
  icon_unlock: require("../assets/Images/icon_unlock.png"),

  card_bg: require("../assets/Images/card_bg.png"),
  badge_main_icon: require("../assets/Images/badge_main_icon.png"),
  badge_icon: require("../assets/Images/badge_icon.png"),
  badge_icon_bg: require("../assets/Images/badge_icon_bg.png"),

  icon_gift: require("../assets/Images/icon_gift.png"),
  survey_abandoned: require("../assets/Images/survey_abandoned.png"),
  BadgedEarned: require("../assets/Images/BadgedEarned.png"),
  icon_wallet_created: require("../assets/Images/icon_wallet_created.png"),
  icon_kyc_completed: require("../assets/Images/icon_kyc_completed.png"),
  onGoing1: require("../assets/Images/join_eq8.png"),
  onGoing2: require("../assets/Images/updateProfile_ongoing.png"),
  onGoing3: require("../assets/Images/participate_ongoing.png"),
  onGoing4: require("../assets/Images/review_and_preview_ongoing.png"),
  onGoing5: require("../assets/Images/compete_ongoing.png"),
  onGoing6: require("../assets/Images/create_ongoing.png"),
  onGoing7: require("../assets/Images/last_onboarding_new.png"),
  onBoardingArrowLeft: require("../assets/Images/onBoarding-arrow-left.png"),
  btnNext: require("../assets/Images/btn_next.png"),
  icon_send_tx: require("../assets/Images/icon_send_tx.png"),
  icon_receive_tx: require("../assets/Images/icon_receive_tx.png"),

  icon_notification: require("../assets/Images/icon_notification.png"),
  icon_black_notification: require("../assets/Images/icon_black_notification.png"),
  icon_red_notification: require("../assets/Images/red_notification.png"),
  icon_red_white_notification: require("../assets/Images/red_white_notification.png"),
  bgNotification: require("../assets/Images/bgNotification.png"),

  card_bg_slider: require("../assets/Images/card_bg_slider.png"),
  join_comunity: require("../assets/Images/card_join_comunity.png"),
  invite_your_friend: require("../assets/Images/card_invite_friend.png"),
  kyc_verification: require("../assets/Images/card_kyc_verification.png"),
  earn_your_badge: require("../assets/Images/card_earn_your_badge.png"),
  icon_card_quiz: require("../assets/Images/icon_card_quiz.png"),
  icon_card_test: require("../assets/Images/icon_card_test.png"),
  icon_card_polls: require("../assets/Images/icon_card_polls.png"),
  icon_card_qnft: require("../assets/Images/icon_card_qnft.png"),
  icon_card_survey: require("../assets/Images/icon_card_survey.png"),
  qnft_arrow: require("../assets/Images/qnft_arrow.png"),
  icon_telegram: require("../assets/Images/icon_telegram.png"),
  icon_eq8_icon: require("../assets/Images/icon_eq8.png"),
  icon_instagram: require("../assets/Images/icon_instagram.png"),
  icon_facebook: require("../assets/Images/icon_facebook.png"),
  icon_twitter: require("../assets/Images/icon_twitter.png"),
  icon_linkedin: require("../assets/Images/icon_linkedin.png"),
  icon_medium: require("../assets/Images/icon_medium.png"),
  icon_youtube: require("../assets/Images/icon_youtube.png"),
  earn_invite: require("../assets/Images/earn_invite.png"),
  icon_refer_eq: require("../assets/Images/icon_refer_eq.png"),
  invite_button_arrow: require("../assets/Images/invite_button_arrow.png"),
  arrow_back_white: require("../assets/Images/arrow_back_white.png"),
  icon_info: require("../assets/Images/icon_info.png"),
  icon_checkbox: require("../assets/Images/icon_checkbox.png"),
  checkboxDefault: require("../assets/Images/checkboxDefault.png"),
  icon_upload_file: require("../assets/Images/icon_upload_file.png"),
  icon_add_other: require("../assets/Images/icon_add_other.png"),
  create_another_qnft_add: require("../assets/Images/create_another_qnft_add.png"),
  icon_minus: require("../assets/Images/remove_field.png"),
  arrow_list: require("../assets/Images/arrow_list.png"),
  bg_ntt_points: require("../assets/Images/bg_ntt_points.png"),
  giftImg: require("../assets/Images/gift.png"),
  icon_join_community: require("../assets/Images/icon_join_community.png"),
  icon_points_next: require("../assets/Images/icon_points_next.png"),
  icon_asset_next: require("../assets/Images/icon_asset_next.png"),
  icon_success: require("../assets/Images/icon_success.png"),
  icon_report: require("../assets/Images/icon_report.png"),

  poll_radios: require("../assets/Images/poll_radios.png"),
  poll_radios_selected: require("../assets/Images/poll_radios_selected.png"),
  poll_completed: require("../assets/Images/poll_completed.png"),
  poll_details_arrow: require("../assets/Images/poll_details_arrow.png"),
  modal_close_icon: require("../assets/Images/modal_close_icon.png"),
  icon_modal_reward: require("../assets/Images/icon_modal_reward.png"),
  icon_audio: require("../assets/Images/audio.png"),
  icon_terms: require("../assets/Images/icon_terms.png"),
};
export default Images;
