const ImagesAssets = {
  //  SunrayLogoImage: require('../hh/logo.png'),
  // EditImage: require('../assets/edit.png'),
  splashBackground320: require("../assets/Images/Android/320x480.png"),
  splashBackground480: require("../assets/Images/Android/480x800.png"),
  splashBackground720: require("../assets/Images/Android/720x1280.png"),
  splashBackground1080: require("../assets/Images/Android/1080x1920.png"),
  splashBackgroundiPhone4: require("../assets/Images/iOS/640x960.png"),
  splashBackgroundiPhone5: require("../assets/Images/iOS/640x1136.png"),
  splashBackgroundiPhone6: require("../assets/Images/iOS/750x1344.png"),
  splashBackgroundiPhoneX: require("../assets/iOS/1125x2436.png"),
  splashBackgroundiPhone7Plus: require("../assets/iOS/1242x2208.png"),
  Background320: require("../assets/Android/BG/320x480.png"),
  Background480: require("../assets/Android/BG/480x800.png"),
  Background720: require("../assets/Android/BG/720x1280.png"),
  Background1080: require("../assets/Android/BG/1080x1920.png"),
  BackgroundiPhone4: require("../assets/iOS/BG/640x960.png"),
  BackgroundiPhone5: require("../assets/iOS/BG/640x1136.png"),
  BackgroundiPhone6: require("../assets/iOS/BG/750x1344.png"),
  BackgroundiPhoneX: require("../assets/iOS/BG/1125x2436.png"),
  BackgroundiPhone7Plus: require("../assets/iOS/BG/1242x2208.png"),
  logo: require("../assets/selection_screen_logo.png"),
  createNew: require("../assets/createnew.png"),
  back: require("../assets/back.png"),
  checkBox: require("../assets/checkbox.png"),
  uncheckBox: require("../assets/uncheck.png"),
  TermsCheck: require("../assets/termcheck.png"),
  Header: require("../assets/header.png"),
  chat: require("../assets/chat.png"),
  Chat_Grey: require("../assets/Chat_Grey.png"),
  dapp: require("../assets/Dapp.png"),
  Dapp_grey: require("../assets/Dapp_Grey.png"),
  Wallet: require("../assets/Wallet.png"),
  Wallet_grey: require("../assets/Wallet_grey.png"),
  Profile: require("../assets/Profile.png"),
  Profile_grey: require("../assets/Profile_Grey.png"),
  notification: require("../assets/notification.png"),
  search: require("../assets/search.png"),
  add: require("../assets/add.png"),
  Bitcoin: require("../assets/Bitcoin.png"),
  card: require("../assets/Card.png"),
  Send: require("../assets/Send.png"),
  Receive: require("../assets/Recieve.png"),
  Transaction: require("../assets/Transaction.png"),
  SendUp: require("../assets/red_up.png"),
  ReceiveDown: require("../assets/green_down.png"),
  Complete: require("../assets/complete.png"),
  Progress: require("../assets/progress.png"),
  failed: require("../assets/failed.png"),
  Qr_code: require("../assets/qr_code.png"),
  dropdown: require("../assets/dropdown.png"),
  dropdownWhite: require("../assets/dropdown_white.png"),
  SplashJson: require("../assets/Keyper.json"),
  LoaderJson: require("../assets/black.json"),
  LoaderWhiteJson: require("../assets/white.json"),
  AddBlack: require("../assets/addBlack.png"),
  backspace: require("../assets/backspace.png"),
  more: require("../assets/more.png"),
  home: require("../assets/home.png"),
  more_white: require("../assets/more_white.png"),
  reload: require("../assets/reload.png"),
  back_browser: require("../assets/back_browser.png"),
  filter: require("../assets/filter.png"),
  downBlack: require("../assets/down_black.png"),
  filterCheck: require("../assets/filter_check.png"),
  filterCheckLight: require("../assets/checked.png"),
  Manage: require("../assets/grid.png"),
  Copy: require("../assets/copy.png"),
  Forgot: require("../assets/forgot.png"),
  Forward: require("../assets/forward.png"),
  Send: require("../assets/Send.png"),
  logo1: require("../assets/logo.jpg"),
  attach: require("../assets/attach.png"),
  receiveIcon: require("../assets/receive.png"),
  sendIcon: require("../assets/sendArrow.png"),
  blockIcon: require("../assets/block.png"),
  scanImage: require("../assets/scan.png"),
  scanImage: require("../assets/scan.png"),
  Eq8loader: require("../assets/Eq8_color.json"),
  eq8_logo_animation: require("../assets/eq8_logo_animation.json"),

  // dropDownArr: require('../assets/refresh_icon.png'),
};
export default ImagesAssets;
//refresh_icon.png
